import { useEffect, useRef, useState, type MouseEvent, type PointerEvent, type ReactElement } from 'react';
import { GameLoop } from '../domain/GameLoop';
import { CHAPTER_DEFINITIONS, getNextChapterDefinition, type ChapterId } from '../content/ChapterDefinitions';
import { M1RunSimulation, type M1RunSnapshot, type RewardId } from '../domain/M1RunSimulation';
import { BrowserLifecycle } from '../infrastructure/BrowserLifecycle';
import { DEFAULT_PROFILE, ProfileRepository, type Profile } from '../infrastructure/ProfileRepository';
import { RunCheckpointRepository } from '../infrastructure/RunCheckpointRepository';
import { ThreeRuntime } from '../rendering/ThreeRuntime';
import { ACHIEVEMENTS } from '../content/Achievements';

const INITIAL_SNAPSHOT = new M1RunSimulation().snapshot();
const rewardNames: Record<RewardId, string> = { storm_bow: '風暴弓｜箭數 +2、箭傷 +40%', lightning_core: '雷網核心｜目標 +1、傷害 +3、距離 +6', heartwood: '心木護佑｜最大 HP +60', deadeye: '獵手印記｜箭傷 +35%', gale_heart: '疾風之心｜箭速 +40%', ironbark: '鐵木護甲｜減傷 +40%、最大 HP +30' };

export function App(): ReactElement {
  const canvasContainerRef = useRef<HTMLDivElement>(null); const runtimeRef = useRef<ThreeRuntime | null>(null); const simulationRef = useRef(new M1RunSimulation()); const checkpointRef = useRef(new RunCheckpointRepository()); const profileRef = useRef(new ProfileRepository()); const pendingCheckpointRef = useRef<M1RunSnapshot | undefined>(undefined); const isMouseDraggingRef = useRef(false);
  const [snapshot, setSnapshot] = useState<M1RunSnapshot>(INITIAL_SNAPSHOT); const [profile, setProfile] = useState<Profile>(DEFAULT_PROFILE); const [screen, setScreen] = useState<'game' | 'shop' | 'achievements'>('game'); const [selectedChapterId, setSelectedChapterId] = useState<ChapterId>('ch01_meadow'); const [selectedCard, setSelectedCard] = useState<RewardId>(); const [hasCheckpoint, setHasCheckpoint] = useState(false); const [isWebGlSupported] = useState(() => document.createElement('canvas').getContext('webgl2') !== null);

  useEffect(() => { void profileRef.current.loadAsync().then(setProfile).catch(() => undefined); void checkpointRef.current.loadAsync().then((checkpoint) => { const saved = checkpoint?.payload as M1RunSnapshot | undefined; if (saved?.phase === 'playing' || saved?.phase === 'reward') { pendingCheckpointRef.current = saved; setHasCheckpoint(true); } }).catch(() => undefined); }, []);
  useEffect(() => {
    const container = canvasContainerRef.current; if (container === null || !isWebGlSupported) return undefined;
    const runtime = new ThreeRuntime(container); runtimeRef.current = runtime; const save = async (): Promise<void> => { const current = simulationRef.current.snapshot(); if (current.phase === 'playing' || current.phase === 'reward') await checkpointRef.current.saveAsync({ runId: 'ch01-active', contentVersion: '0.2.0', savedAtMs: Date.now(), simulationTick: Math.floor(current.elapsedSeconds * 30), payload: current }); };
    const lifecycle = new BrowserLifecycle({ onSuspend: save, onResume: () => undefined });
    const gameLoop = new GameLoop({ tick: (deltaSeconds) => simulationRef.current.tick(deltaSeconds) }, () => { const next = simulationRef.current.snapshot(); runtime.sync(next); runtime.render(); setSnapshot(next); });
    const onResize = (): void => runtime.resize(); lifecycle.start(); gameLoop.start(); window.addEventListener('resize', onResize);
    return () => { window.removeEventListener('resize', onResize); lifecycle.stop(); gameLoop.stop(); runtime.dispose(); runtimeRef.current = null; };
  }, [isWebGlSupported]);

  useEffect(() => { runtimeRef.current?.setQuality(profile.qualityMode); }, [profile.qualityMode]);

  const startRun = (): void => { setScreen('game'); setSelectedCard(undefined); setHasCheckpoint(false); simulationRef.current.start(profile, selectedChapterId); setSnapshot(simulationRef.current.snapshot()); };
  const continueChapter = (): void => { if (simulationRef.current.continueToNextChapter()) { setSelectedCard(undefined); setSnapshot(simulationRef.current.snapshot()); } };
  const resumeRun = (): void => { const saved = pendingCheckpointRef.current; if (saved === undefined || !simulationRef.current.restore(saved)) return; setScreen('game'); setHasCheckpoint(false); setSnapshot(simulationRef.current.snapshot()); };
  const movePlayerFromClientX = (clientX: number, element: HTMLDivElement): void => { if (simulationRef.current.snapshot().phase !== 'playing') return; const bounds = element.getBoundingClientRect(); simulationRef.current.setTargetX((((clientX - bounds.left) / bounds.width) * 2 - 1) * 5); };
  const onPointerDown = (event: PointerEvent<HTMLDivElement>): void => { event.currentTarget.setPointerCapture(event.pointerId); movePlayerFromClientX(event.clientX, event.currentTarget); };
  const onPointerMove = (event: PointerEvent<HTMLDivElement>): void => { movePlayerFromClientX(event.clientX, event.currentTarget); };
  const onMouseDown = (event: MouseEvent<HTMLDivElement>): void => { isMouseDraggingRef.current = true; movePlayerFromClientX(event.clientX, event.currentTarget); };
  const onMouseMove = (event: MouseEvent<HTMLDivElement>): void => { if (isMouseDraggingRef.current) movePlayerFromClientX(event.clientX, event.currentTarget); };
  const onMouseUp = (): void => { isMouseDraggingRef.current = false; };
  const confirmReward = (): void => { if (selectedCard === undefined || !simulationRef.current.chooseReward(selectedCard)) return; const next = simulationRef.current.snapshot(); setSnapshot(next); const chapterIndex = CHAPTER_DEFINITIONS.find((chapter) => chapter.id === next.chapterId)?.index ?? 1; const chapterAchievements = ['first_rift', 'mirror_route', 'ember_heart', undefined, undefined, 'sixfold_thread']; const achievementIds = [...new Set([...profile.achievementIds, 'echo_choice', chapterAchievements[chapterIndex - 1]].filter((id): id is string => id !== undefined))]; const updated = { ...profile, gold: profile.gold + next.earnedGold, unlockedChapterIndex: Math.max(profile.unlockedChapterIndex, Math.min(6, chapterIndex + 1)), achievementIds }; setProfile(updated); void profileRef.current.saveAsync(updated); void checkpointRef.current.clearAsync(); };
  const buy = (key: UpgradeKey): void => { const cost = 20 + profile[key] * 15; if (profile.gold < cost || profile[key] >= 5) return; const updated = { ...profile, gold: profile.gold - cost, [key]: profile[key] + 1, achievementIds: [...new Set([...profile.achievementIds, 'permanent_hand'])] }; setProfile(updated); void profileRef.current.saveAsync(updated); };
  const setQuality = (qualityMode: Profile['qualityMode']): void => { const updated = { ...profile, qualityMode }; setProfile(updated); void profileRef.current.saveAsync(updated); };
  if (!isWebGlSupported) return <main className="unsupported-screen"><h1>此裝置暫不支援</h1><p>Arrow a Row 需要 WebGL 2。</p></main>;
  return <main className="app-shell"><div ref={canvasContainerRef} className="game-canvas" aria-hidden="true" onPointerDown={onPointerDown} onPointerMove={onPointerMove} onMouseDown={onMouseDown} onMouseMove={onMouseMove} onMouseUp={onMouseUp} onMouseLeave={onMouseUp} />
    {screen === 'shop' ? <Shop profile={profile} onBuy={buy} onBack={() => setScreen('game')} /> : screen === 'achievements' ? <Achievements profile={profile} onBack={() => setScreen('game')} /> : <>
      {snapshot.phase === 'playing' && <RunHud snapshot={snapshot} />}
      {snapshot.phase === 'menu' && <MainMenu onStart={startRun} onResume={hasCheckpoint ? resumeRun : undefined} onShop={() => setScreen('shop')} onAchievements={() => setScreen('achievements')} gold={profile.gold} unlockedChapterIndex={profile.unlockedChapterIndex} selectedChapterId={selectedChapterId} onSelectChapter={setSelectedChapterId} qualityMode={profile.qualityMode} onSetQuality={setQuality} />}
      {snapshot.phase === 'reward' && <RewardScreen snapshot={snapshot} selected={selectedCard} onSelect={setSelectedCard} onConfirm={confirmReward} />}
      {snapshot.phase === 'dead' && <ResultScreen title="本局結束" detail="光軌尚未熄滅。" onRestart={startRun} onShop={() => setScreen('shop')} />}
      {snapshot.phase === 'complete' && <ResultScreen title={`${snapshot.chapterTitle}完成`} detail={`獲得 ${snapshot.earnedGold} 金幣；目前 Build 會帶入下一章。`} onRestart={startRun} onShop={() => setScreen('shop')} onNext={getNextChapterDefinition(snapshot.chapterId) === undefined ? undefined : continueChapter} nextTitle={getNextChapterDefinition(snapshot.chapterId)?.title} />}
    </>}</main>;
}
function MainMenu({ onStart, onResume, onShop, onAchievements, gold, unlockedChapterIndex, selectedChapterId, onSelectChapter, qualityMode, onSetQuality }: { readonly onStart: () => void; readonly onResume: (() => void) | undefined; readonly onShop: () => void; readonly onAchievements: () => void; readonly gold: number; readonly unlockedChapterIndex: number; readonly selectedChapterId: ChapterId; readonly onSelectChapter: (id: ChapterId) => void; readonly qualityMode: Profile['qualityMode']; readonly onSetQuality: (mode: Profile['qualityMode']) => void }): ReactElement { return <section className="main-menu" aria-label="主選單"><p className="eyebrow">六章灰盒</p><h1>Arrow a Row</h1><p>{onResume === undefined ? '選擇已解鎖章節後，單手拖曳，選擇路徑，自動射擊。' : '一段光軌仍在等待你。'}</p><div className="chapter-select">{CHAPTER_DEFINITIONS.map((chapter) => <button className={chapter.id === selectedChapterId ? 'selected' : 'secondary'} disabled={chapter.index > unlockedChapterIndex} key={chapter.id} type="button" onClick={() => onSelectChapter(chapter.id)}>CH{chapter.index}｜{chapter.index > unlockedChapterIndex ? '未解鎖' : chapter.title}</button>)}</div>{onResume !== undefined && <button type="button" onClick={onResume}>繼續本局</button>}<button type="button" onClick={onStart}>開始 {CHAPTER_DEFINITIONS.find((chapter) => chapter.id === selectedChapterId)?.title}</button><button type="button" className="secondary" onClick={onShop}>永久強化｜{gold} 金幣</button><button type="button" className="secondary" onClick={onAchievements}>成就</button><div className="quality-control" aria-label="畫質設定"><span>畫質</span><button className={qualityMode === 'standard' ? 'selected' : 'secondary'} type="button" onClick={() => onSetQuality('standard')}>標準 60 FPS</button><button className={qualityMode === 'low' ? 'selected' : 'secondary'} type="button" onClick={() => onSetQuality('low')}>省電 30 FPS</button></div></section>; }
function RunHud({ snapshot }: { readonly snapshot: M1RunSnapshot }): ReactElement { const bossNames: Record<ChapterId, string> = { ch01_meadow: '苔冠守衛', ch02_viaduct: '鏡潮校準者', ch03_forge: '熔脈監工', ch04_canopy: '枝語母體', ch05_archive: '無光抄錄者', ch06_horizon: '靜滯之核' }; const player = snapshot.player; return <><header className="hud"><p>{snapshot.chapterTitle}｜HP {Math.ceil(player.hp)} / {player.maxHp}</p><p>{player.projectileCount} 箭｜晶塵 {snapshot.collectedShards}</p></header><section className="build-hud" aria-label="目前 Build"><strong>Build</strong><span>箭 {player.projectileCount}</span><span>穿透 {player.pierceCount}</span><span>箭速 {Math.round(player.arrowSpeed)}</span><span>射速 +{Math.round((1 / player.fireRateMultiplier - 1) * 100)}%</span><span>⚡ {player.lightningTargetCount} 目標</span><span>⚡ {player.lightningDamagePerSecond}/秒</span><span>⚡ {player.lightningRange} 距離</span><span>減傷 {Math.round(player.damageReduction * 100)}%</span></section>{snapshot.distanceMeters < 12 && <p className="aim-hint">箭矢只往正前方射出，拖曳角色對準敵人。</p>}{snapshot.boss !== undefined ? <section className="boss-hud"><strong>{bossNames[snapshot.chapterId]}｜P{snapshot.boss.phase}</strong><progress value={snapshot.boss.hp} max={snapshot.boss.maxHp} />{snapshot.boss.telegraphSeconds > 0 && <p>{snapshot.boss.telegraphText}</p>}</section> : <p className="run-progress">距離 {Math.floor(snapshot.distanceMeters)}m / Boss</p>}</>; }
function RewardScreen({ snapshot, selected, onSelect, onConfirm }: { readonly snapshot: M1RunSnapshot; readonly selected: RewardId | undefined; readonly onSelect: (id: RewardId) => void; readonly onConfirm: () => void }): ReactElement { return <section className="modal-card" aria-label="選擇一份回響"><h1>選擇一份回響</h1><p>苔冠重新聽見了風。</p>{snapshot.rewardOptions.map((id) => <button className={selected === id ? 'selected' : 'secondary'} key={id} type="button" onClick={() => onSelect(id)}>{rewardNames[id]}</button>)}<button type="button" disabled={selected === undefined} onClick={onConfirm}>確認選擇</button></section>; }
function ResultScreen({ title, detail, onRestart, onShop, onNext, nextTitle }: { readonly title: string; readonly detail: string; readonly onRestart: () => void; readonly onShop: () => void; readonly onNext?: (() => void) | undefined; readonly nextTitle?: string | undefined }): ReactElement { return <section className="main-menu" aria-label={title}><h1>{title}</h1><p>{detail}</p>{onNext !== undefined && <button type="button" onClick={onNext}>前往 {nextTitle}</button>}<button type="button" className="secondary" onClick={onRestart}>重新開始</button><button type="button" className="secondary" onClick={onShop}>前往商店</button></section>; }
type UpgradeKey = 'healthLevel' | 'damageLevel' | 'fireRateLevel' | 'arrowSpeedLevel' | 'pierceLevel' | 'movementLevel';
function Shop({ profile, onBuy, onBack }: { readonly profile: Profile; readonly onBuy: (key: UpgradeKey) => void; readonly onBack: () => void }): ReactElement { const items: Array<readonly [UpgradeKey, string]> = [['healthLevel', '曙光體魄'], ['damageLevel', '弓弦研磨'], ['fireRateLevel', '迅捷弦律'], ['arrowSpeedLevel', '流光箭簇'], ['pierceLevel', '破界箭頭'], ['movementLevel', '踏風步伐']]; return <section className="modal-card" aria-label="永久強化"><h1>永久強化</h1><p>金幣：{profile.gold}</p>{items.map(([key, label]) => { const cost = 20 + profile[key] * 15; return <div className="shop-item" key={key}><span>{label} Lv.{profile[key]}</span><button type="button" disabled={profile.gold < cost || profile[key] >= 5} onClick={() => onBuy(key)}>購買 {cost} 金幣</button></div>; })}<button type="button" className="secondary" onClick={onBack}>返回</button></section>; }
function Achievements({ profile, onBack }: { readonly profile: Profile; readonly onBack: () => void }): ReactElement { return <section className="modal-card" aria-label="成就"><h1>成就｜{profile.achievementIds.length} / {ACHIEVEMENTS.length}</h1>{ACHIEVEMENTS.map((achievement) => <p className="achievement-item" key={achievement.id}>{profile.achievementIds.includes(achievement.id) ? '✦' : '○'} {achievement.title}｜{achievement.description}</p>)}<button type="button" className="secondary" onClick={onBack}>返回</button></section>; }
