import { useEffect, useRef, useState, type MouseEvent, type PointerEvent, type ReactElement } from 'react';
import { GameLoop } from '../domain/GameLoop';
import { CHAPTER_DEFINITIONS, getNextChapterDefinition, type ChapterId } from '../content/ChapterDefinitions';
import { M1RunSimulation, type M1RunSnapshot, type RewardId } from '../domain/M1RunSimulation';
import { BrowserLifecycle } from '../infrastructure/BrowserLifecycle';
import { DEFAULT_PROFILE, ProfileRepository, type Profile } from '../infrastructure/ProfileRepository';
import { RunCheckpointRepository } from '../infrastructure/RunCheckpointRepository';
import { ThreeRuntime } from '../rendering/ThreeRuntime';

const INITIAL_SNAPSHOT = new M1RunSimulation().snapshot();
const rewardNames: Record<RewardId, string> = { storm_bow: '風暴弓｜箭數 +2', blade_nexus: '刃環核心｜飛劍 +2', heartwood: '心木護佑｜最大 HP +60' };

export function App(): ReactElement {
  const canvasContainerRef = useRef<HTMLDivElement>(null); const simulationRef = useRef(new M1RunSimulation()); const checkpointRef = useRef(new RunCheckpointRepository()); const profileRef = useRef(new ProfileRepository()); const pendingCheckpointRef = useRef<M1RunSnapshot | undefined>(undefined); const isMouseDraggingRef = useRef(false);
  const [snapshot, setSnapshot] = useState<M1RunSnapshot>(INITIAL_SNAPSHOT); const [profile, setProfile] = useState<Profile>(DEFAULT_PROFILE); const [screen, setScreen] = useState<'game' | 'shop'>('game'); const [selectedChapterId, setSelectedChapterId] = useState<ChapterId>('ch01_meadow'); const [selectedCard, setSelectedCard] = useState<RewardId>(); const [hasCheckpoint, setHasCheckpoint] = useState(false); const [isWebGlSupported] = useState(() => document.createElement('canvas').getContext('webgl2') !== null);

  useEffect(() => { void profileRef.current.loadAsync().then(setProfile).catch(() => undefined); void checkpointRef.current.loadAsync().then((checkpoint) => { const saved = checkpoint?.payload as M1RunSnapshot | undefined; if (saved?.phase === 'playing' || saved?.phase === 'reward') { pendingCheckpointRef.current = saved; setHasCheckpoint(true); } }).catch(() => undefined); }, []);
  useEffect(() => {
    const container = canvasContainerRef.current; if (container === null || !isWebGlSupported) return undefined;
    const runtime = new ThreeRuntime(container); const save = async (): Promise<void> => { const current = simulationRef.current.snapshot(); if (current.phase === 'playing' || current.phase === 'reward') await checkpointRef.current.saveAsync({ runId: 'ch01-active', contentVersion: '0.2.0', savedAtMs: Date.now(), simulationTick: Math.floor(current.elapsedSeconds * 30), payload: current }); };
    const lifecycle = new BrowserLifecycle({ onSuspend: save, onResume: () => undefined });
    const gameLoop = new GameLoop({ tick: (deltaSeconds) => simulationRef.current.tick(deltaSeconds) }, () => { const next = simulationRef.current.snapshot(); runtime.sync(next); runtime.render(); setSnapshot(next); });
    const onResize = (): void => runtime.resize(); lifecycle.start(); gameLoop.start(); window.addEventListener('resize', onResize);
    return () => { window.removeEventListener('resize', onResize); lifecycle.stop(); gameLoop.stop(); runtime.dispose(); };
  }, [isWebGlSupported]);

  const startRun = (): void => { setScreen('game'); setSelectedCard(undefined); setHasCheckpoint(false); simulationRef.current.start(profile, selectedChapterId); setSnapshot(simulationRef.current.snapshot()); };
  const continueChapter = (): void => { if (simulationRef.current.continueToNextChapter()) { setSelectedCard(undefined); setSnapshot(simulationRef.current.snapshot()); } };
  const resumeRun = (): void => { const saved = pendingCheckpointRef.current; if (saved === undefined || !simulationRef.current.restore(saved)) return; setScreen('game'); setHasCheckpoint(false); setSnapshot(simulationRef.current.snapshot()); };
  const movePlayerFromClientX = (clientX: number, element: HTMLDivElement): void => { if (simulationRef.current.snapshot().phase !== 'playing') return; const bounds = element.getBoundingClientRect(); simulationRef.current.setTargetX((((clientX - bounds.left) / bounds.width) * 2 - 1) * 5); };
  const onPointerDown = (event: PointerEvent<HTMLDivElement>): void => { event.currentTarget.setPointerCapture(event.pointerId); movePlayerFromClientX(event.clientX, event.currentTarget); };
  const onPointerMove = (event: PointerEvent<HTMLDivElement>): void => { movePlayerFromClientX(event.clientX, event.currentTarget); };
  const onMouseDown = (event: MouseEvent<HTMLDivElement>): void => { isMouseDraggingRef.current = true; movePlayerFromClientX(event.clientX, event.currentTarget); };
  const onMouseMove = (event: MouseEvent<HTMLDivElement>): void => { if (isMouseDraggingRef.current) movePlayerFromClientX(event.clientX, event.currentTarget); };
  const onMouseUp = (): void => { isMouseDraggingRef.current = false; };
  const confirmReward = (): void => { if (selectedCard === undefined || !simulationRef.current.chooseReward(selectedCard)) return; const next = simulationRef.current.snapshot(); setSnapshot(next); const updated = { ...profile, gold: profile.gold + next.earnedGold }; setProfile(updated); void profileRef.current.saveAsync(updated); void checkpointRef.current.clearAsync(); };
  const buy = (key: 'healthLevel' | 'damageLevel' | 'fireRateLevel'): void => { const cost = 20 + profile[key] * 15; if (profile.gold < cost || profile[key] >= 5) return; const updated = { ...profile, gold: profile.gold - cost, [key]: profile[key] + 1 }; setProfile(updated); void profileRef.current.saveAsync(updated); };
  if (!isWebGlSupported) return <main className="unsupported-screen"><h1>此裝置暫不支援</h1><p>Arrow a Row 需要 WebGL 2。</p></main>;
  return <main className="app-shell"><div ref={canvasContainerRef} className="game-canvas" aria-hidden="true" onPointerDown={onPointerDown} onPointerMove={onPointerMove} onMouseDown={onMouseDown} onMouseMove={onMouseMove} onMouseUp={onMouseUp} onMouseLeave={onMouseUp} />
    {screen === 'shop' ? <Shop profile={profile} onBuy={buy} onBack={() => setScreen('game')} /> : <>
      {snapshot.phase === 'playing' && <RunHud snapshot={snapshot} />}
      {snapshot.phase === 'menu' && <MainMenu onStart={startRun} onResume={hasCheckpoint ? resumeRun : undefined} onShop={() => setScreen('shop')} gold={profile.gold} selectedChapterId={selectedChapterId} onSelectChapter={setSelectedChapterId} />}
      {snapshot.phase === 'reward' && <RewardScreen snapshot={snapshot} selected={selectedCard} onSelect={setSelectedCard} onConfirm={confirmReward} />}
      {snapshot.phase === 'dead' && <ResultScreen title="本局結束" detail="光軌尚未熄滅。" onRestart={startRun} onShop={() => setScreen('shop')} />}
      {snapshot.phase === 'complete' && <ResultScreen title={`${snapshot.chapterTitle}完成`} detail={`獲得 ${snapshot.earnedGold} 金幣；目前 Build 會帶入下一章。`} onRestart={startRun} onShop={() => setScreen('shop')} onNext={getNextChapterDefinition(snapshot.chapterId) === undefined ? undefined : continueChapter} nextTitle={getNextChapterDefinition(snapshot.chapterId)?.title} />}
    </>}</main>;
}
function MainMenu({ onStart, onResume, onShop, gold, selectedChapterId, onSelectChapter }: { readonly onStart: () => void; readonly onResume: (() => void) | undefined; readonly onShop: () => void; readonly gold: number; readonly selectedChapterId: ChapterId; readonly onSelectChapter: (id: ChapterId) => void }): ReactElement { return <section className="main-menu" aria-label="主選單"><p className="eyebrow">六章灰盒</p><h1>Arrow a Row</h1><p>{onResume === undefined ? '選擇章節後，單手拖曳，選擇路徑，自動射擊。' : '一段光軌仍在等待你。'}</p><div className="chapter-select">{CHAPTER_DEFINITIONS.map((chapter) => <button className={chapter.id === selectedChapterId ? 'selected' : 'secondary'} key={chapter.id} type="button" onClick={() => onSelectChapter(chapter.id)}>CH{chapter.index}｜{chapter.title}</button>)}</div>{onResume !== undefined && <button type="button" onClick={onResume}>繼續本局</button>}<button type="button" onClick={onStart}>開始 {CHAPTER_DEFINITIONS.find((chapter) => chapter.id === selectedChapterId)?.title}</button><button type="button" className="secondary" onClick={onShop}>永久強化｜{gold} 金幣</button></section>; }
function RunHud({ snapshot }: { readonly snapshot: M1RunSnapshot }): ReactElement { const bossName = snapshot.chapterId === 'ch02_viaduct' ? '鏡潮校準者' : '苔冠守衛'; return <><header className="hud"><p>{snapshot.chapterTitle}｜HP {Math.ceil(snapshot.player.hp)} / {snapshot.player.maxHp}</p><p>{snapshot.player.projectileCount} 箭｜晶塵 {snapshot.collectedShards}</p></header>{snapshot.boss !== undefined ? <section className="boss-hud"><strong>{bossName}｜P{snapshot.boss.phase}</strong><progress value={snapshot.boss.hp} max={snapshot.boss.maxHp} />{snapshot.boss.telegraphSeconds > 0 && <p>{snapshot.boss.telegraphText}</p>}</section> : <p className="run-progress">距離 {Math.floor(snapshot.distanceMeters)}m / Boss</p>}</>; }
function RewardScreen({ snapshot, selected, onSelect, onConfirm }: { readonly snapshot: M1RunSnapshot; readonly selected: RewardId | undefined; readonly onSelect: (id: RewardId) => void; readonly onConfirm: () => void }): ReactElement { return <section className="modal-card" aria-label="選擇一份回響"><h1>選擇一份回響</h1><p>苔冠重新聽見了風。</p>{snapshot.rewardOptions.map((id) => <button className={selected === id ? 'selected' : 'secondary'} key={id} type="button" onClick={() => onSelect(id)}>{rewardNames[id]}</button>)}<button type="button" disabled={selected === undefined} onClick={onConfirm}>確認選擇</button></section>; }
function ResultScreen({ title, detail, onRestart, onShop, onNext, nextTitle }: { readonly title: string; readonly detail: string; readonly onRestart: () => void; readonly onShop: () => void; readonly onNext?: (() => void) | undefined; readonly nextTitle?: string | undefined }): ReactElement { return <section className="main-menu" aria-label={title}><h1>{title}</h1><p>{detail}</p>{onNext !== undefined && <button type="button" onClick={onNext}>前往 {nextTitle}</button>}<button type="button" className="secondary" onClick={onRestart}>重新開始</button><button type="button" className="secondary" onClick={onShop}>前往商店</button></section>; }
function Shop({ profile, onBuy, onBack }: { readonly profile: Profile; readonly onBuy: (key: 'healthLevel' | 'damageLevel' | 'fireRateLevel') => void; readonly onBack: () => void }): ReactElement { const items: Array<readonly ['healthLevel' | 'damageLevel' | 'fireRateLevel', string]> = [['healthLevel', '曙光體魄'], ['damageLevel', '弓弦研磨'], ['fireRateLevel', '迅捷弦律']]; return <section className="modal-card" aria-label="永久強化"><h1>永久強化</h1><p>金幣：{profile.gold}</p>{items.map(([key, label]) => { const cost = 20 + profile[key] * 15; return <div className="shop-item" key={key}><span>{label} Lv.{profile[key]}</span><button type="button" disabled={profile.gold < cost || profile[key] >= 5} onClick={() => onBuy(key)}>購買 {cost} 金幣</button></div>; })}<button type="button" className="secondary" onClick={onBack}>返回</button></section>; }
